const events = [
  { type:'flight', start:'2026-07-19', end:'2026-07-19', icon:'✈', label:'International flight · PNR 88AOXJ', title:'New Delhi → Zurich', meta:'19 Jul · Arrive 19:00', summary:'Etihad Airways via Abu Dhabi', details:[['Reservation','PNR 88AOXJ · 4 adults'],['EY 213','DEL 09:25 → AUH 11:35 · 3h 40m'],['Layover','2h 30m · Terminal A'],['EY 141','AUH 14:05 → ZRH 19:00 · 6h 55m'],['Checked baggage','30 kg per adult'],['Cabin baggage','7 kg per adult']], map:'https://www.google.com/maps/search/?api=1&query=Zurich+Airport' },
  { type:'stay', start:'2026-07-19', end:'2026-07-20', icon:'🏨', city:'Zurich Airport', country:'Switzerland', title:'Zurich Airport', meta:'19–20 Jul · 1 night', hotel:'Hilton Zurich Airport', room:'2 Queen Guest Rooms · Breakfast included', address:'[Hohenbuehlstrasse 10, 8152 Zurich](https://www.google.com/maps/search/Hohenbuehlstrasse%0D%0A+10,+8152+Zurich?entry=gmail&source=g)', image:'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=1200&q=85', about:'Switzerland’s largest city blends a beautiful old town with a sparkling lake and an exceptionally easy transport network.', facts:['Language · German','Currency · CHF','Avg July · 25°C'], highlights:['Lake Zurich','Old Town','Bahnhofstrasse'], nearby:[{name:'The Circle', type:'Airport district', note:'Closest easy evening stop for coffee, shops and a relaxed stroll near the hotel.', mapQuery:'The Circle Zurich Airport'},{name:'Niederdorf in Zurich Old Town', type:'Historic center', note:'Best area for a first walk, local bars and the classic old-town atmosphere.', mapQuery:'Niederdorf Zurich'},{name:'Burkliplatz Market & Lake Promenade', type:'Market and lakeside', note:'Good pick for a city-centre market stop and a walk along Lake Zurich.', mapQuery:'Burkliplatz Zurich'}], plans:[['19 Jul','Arrive, transfer and settle in']], map:'https://www.google.com/maps/search/?api=1&query=Hilton+Zurich+Airport' },
  { type:'transfer', start:'2026-07-20', end:'2026-07-20', icon:'🚆', label:'Rail transfer', title:'Zurich Airport → Lucerne', meta:'20 Jul · ~1h 12m', summary:'IR13 / IR70 · Swiss Pass', details:[['Board','Zurich Flughafen'],['Arrive','Lucerne Station'],['Ticket','Covered by Swiss Pass']], map:'https://www.google.com/maps/dir/?api=1&origin=Zurich+Airport&destination=Lucerne+Station&travelmode=transit' },
  { type:'stay', start:'2026-07-20', end:'2026-07-22', icon:'🏨', city:'Lucerne', country:'Switzerland', title:'Lucerne', meta:'20–22 Jul · 2 nights', hotel:'Radisson Blu Lucerne', room:'2 Twin / Double Rooms · Breakfast included', address:'Lakefront Center, [Inseliquai 12, 6005 Lucerne](https://www.google.com/maps/search/Inseliquai+12,+6005+Lucerne?entry=gmail&source=g)', image:'https://images.unsplash.com/photo-1504218727796-db522606b16f?auto=format&fit=crop&w=1200&q=85', about:'A compact lakeside city framed by mountains, known for its medieval timber bridge and effortless access to Alpine excursions.', facts:['Language · German','Currency · CHF','Avg July · 25°C'], highlights:['Chapel Bridge','Lion Monument','Lake Lucerne'], nearby:[{name:'Chapel Bridge and the Reuss waterfront', type:'Classic first walk', note:'The signature Lucerne stroll and an easy walk from the hotel.', mapQuery:'Kapellbrucke Lucerne'},{name:'Kornmarkt and Old Town', type:'City center', note:'Historic squares, painted facades and the most central part of Lucerne to linger in.', mapQuery:'Kornmarkt Lucerne'},{name:'Lake Lucerne promenade', type:'Lakeside hangout', note:'A relaxed waterfront route near the hotel for views, cruise departures and evening walks.', mapQuery:'Nationalquai Lucerne'}], plans:[['20 Jul','Chapel Bridge, Lion Monument & lake cruise'],['21 Jul','Mt. Titlis & Ice Flyer']], map:'https://www.google.com/maps/search/?api=1&query=Radisson+Blu+Hotel+Lucerne' },
  { type:'transfer', start:'2026-07-22', end:'2026-07-22', icon:'🚆', label:'Alpine rail', title:'Lucerne → Zermatt', meta:'22 Jul · ~3h 17m', summary:'Scenic connections · Swiss Pass', details:[['Leave','Lucerne Station'],['Arrive','Car-free Zermatt'],['Tip','Keep a light layer handy']], map:'https://www.google.com/maps/dir/?api=1&origin=Lucerne+Station&destination=Zermatt+Station&travelmode=transit' },
  { type:'stay', start:'2026-07-22', end:'2026-07-24', icon:'🏨', city:'Zermatt', country:'Switzerland', title:'Zermatt', meta:'22–24 Jul · 2 nights', hotel:'Hotel Continental', room:'2 Double Rooms · Breakfast included', address:'[Brantschenhaus 3](https://www.google.com/maps/search/Brantschenhaus+3?entry=gmail&source=g), 3920 Zermatt', image:'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=85', about:'A car-free Alpine village beneath the Matterhorn, with dramatic cable-car journeys, glacier views and charming lanes.', facts:['Altitude · 1,608 m','Car-free village','Avg July · 20°C'], highlights:['Matterhorn','Glacier Paradise','Ice Palace'], nearby:[{name:'Bahnhofstrasse', type:'Main street', note:'The village spine for shops, bakeries and an easy first wander from the station side.', mapQuery:'Bahnhofstrasse Zermatt'},{name:'Hinterdorfstrasse Old Village', type:'Historic quarter', note:'Traditional wooden barns and a quieter, older side of Zermatt close to the centre.', mapQuery:'Hinterdorfstrasse Zermatt'},{name:'Matterhorn Museum and Kirchplatz', type:'Village core', note:'A compact central area where the museum, church square and cafes cluster together.', mapQuery:'Matterhorn Museum Zermatt'}], plans:[['22 Jul','Check in & explore at leisure'],['23 Jul','Matterhorn Glacier Paradise & Ice Palace']], map:'https://www.google.com/maps/search/?api=1&query=Hotel+Continental+Zermatt' },
  { type:'transfer', start:'2026-07-24', end:'2026-07-24', icon:'🚆', label:'Rail transfer', title:'Zermatt → Zurich', meta:'24 Jul · ~3h 25m', summary:'Swiss rail · Hotel 9 mins from station', details:[['Leave','Zermatt Station'],['Arrive','Zurich HB'],['Transfer','Approx. 9 mins to hotel']], map:'https://www.google.com/maps/dir/?api=1&origin=Zermatt+Station&destination=Zurich+HB&travelmode=transit' },
  { type:'stay', start:'2026-07-24', end:'2026-07-26', icon:'🏨', city:'Zurich', country:'Switzerland', title:'Zurich', meta:'24–26 Jul · 2 nights', hotel:'Mercure Zürich City', room:'2 Comfort Double Rooms · Breakfast included', address:'[Vulkanstrasse 108b, 8048 Zurich](https://www.google.com/maps/search/Vulkanstrasse+108b,%0D%0A+8048+Zurich?entry=gmail&source=g)', image:'https://images.unsplash.com/photo-1573108724029-4c46571d6490?auto=format&fit=crop&w=1200&q=85', about:'A polished lakeside city where medieval streets, contemporary culture and waterfront life sit side by side.', facts:['Language · German','Currency · CHF','Avg July · 25°C'], highlights:['Lake Zurich','Altstadt','Limmat River'], nearby:[{name:'Markthalle Im Viadukt', type:'Local market hall', note:'A strong near-hotel option for local food stalls, design shops and a Zurich West feel.', mapQuery:'Markthalle Im Viadukt Zurich'},{name:'Frau Gerolds Garten', type:'Local hangout', note:'Open-air urban hangout for coffee, drinks and a livelier neighbourhood atmosphere.', mapQuery:'Frau Gerolds Garten Zurich'},{name:'Niederdorf and the Old Town', type:'Historic center', note:'The best area to walk old streets, stop for dinner and feel the city centre.', mapQuery:'Niederdorf Zurich'},{name:'Burkliplatz Market', type:'Market and lakefront', note:'A practical combine of market browsing and a Lake Zurich promenade walk.', mapQuery:'Burkliplatz Zurich'}], plans:[['24 Jul','Check in & rest'],['25 Jul','City exploration & lake cruise']], map:'https://www.google.com/maps/search/?api=1&query=Mercure+Zürich+City' },
  { type:'transfer', start:'2026-07-26', end:'2026-07-26', icon:'🚆', label:'International rail', title:'Zurich → Salzburg', meta:'26 Jul · ~7h 02m', summary:'Zurich HB to Salzburg Hbf', details:[['Board','Zurich HB'],['Journey','Across Switzerland & Austria'],['Arrive','Salzburg Central Station']], map:'https://www.google.com/maps/dir/?api=1&origin=Zurich+HB&destination=Salzburg+Central+Station&travelmode=transit' },
  { type:'stay', start:'2026-07-26', end:'2026-07-28', icon:'🏨', city:'Salzburg', country:'Austria', title:'Salzburg', meta:'26–28 Jul · 2 nights', hotel:'PLAZA Premium Salzburg', room:'2 Comfort Double Rooms · Breakfast included', address:'[Linzer Bundesstrasse 6, 5020 Salzburg](https://www.google.com/maps/search/Linzer+Bundesstrasse%0D%0A+6,+5020+Salzburg?entry=gmail&source=g)', image:'https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?auto=format&fit=crop&w=1200&q=85', about:'Mozart’s elegant hometown is a storybook mix of baroque domes, fortress views and lanes set beneath green hills.', facts:['Language · German','Currency · EUR','Avg July · 25°C'], highlights:['Old Town','Hohensalzburg','Mirabell Gardens'], nearby:[{name:'Linzergasse', type:'Local shopping street', note:'A convenient near-hotel street for cafes, shops and a more local Salzburg rhythm.', mapQuery:'Linzergasse Salzburg'},{name:'Mirabell Gardens', type:'City landmark', note:'One of the easiest major sights to combine with a gentle walk toward the centre.', mapQuery:'Mirabell Gardens Salzburg'},{name:'Getreidegasse', type:'Old Town classic', note:'The most atmospheric central street for signs, boutiques and Mozart links.', mapQuery:'Getreidegasse Salzburg'},{name:'Mozartplatz and Residenzplatz', type:'Historic squares', note:'These are the main Old Town meeting points and a good place to pause in the centre.', mapQuery:'Mozartplatz Salzburg'}], plans:[['26 Jul','Check in & explore at leisure'],['27 Jul','Half-day guided Hallstatt tour']], map:'https://www.google.com/maps/search/?api=1&query=PLAZA+Premium+Salzburg' },
  { type:'transfer', start:'2026-07-28', end:'2026-07-28', icon:'🚆', label:'Rail transfer', title:'Salzburg → Vienna', meta:'28 Jul · ~2h 25m', summary:'Salzburg Hbf to Vienna Hbf', details:[['Board','Salzburg Central'],['Arrive','Vienna Central'],['Then','Transfer to hotel']], map:'https://www.google.com/maps/dir/?api=1&origin=Salzburg+Central+Station&destination=Vienna+Central+Station&travelmode=transit' },
  { type:'stay', start:'2026-07-28', end:'2026-07-31', icon:'🏨', city:'Vienna', country:'Austria', title:'Vienna', meta:'28–31 Jul · 3 nights', hotel:'Leonardo Hotel Vienna City West', room:'2 Comfort Double Rooms · Breakfast included', address:'[Graumanngasse 3–5](https://www.google.com/maps/search/Graumanngasse%0D%0A+3%E2%80%935?entry=gmail&source=g), 1150 Vienna', image:'https://images.unsplash.com/photo-1516550893923-42d28e5677af?auto=format&fit=crop&w=1200&q=85', about:'An imperial capital of palaces, coffee houses, music and grand boulevards—best enjoyed at an unhurried pace.', facts:['Language · German','Currency · EUR','Avg July · 27°C'], highlights:['Schönbrunn','Ringstrasse','Coffee houses'], nearby:[{name:'Meiselmarkt', type:'Local market', note:'A practical west-side stop near the hotel for produce stalls and everyday Vienna.', mapQuery:'Meiselmarkt Vienna'},{name:'Schönbrunn Palace and Gardens', type:'Major sight nearby', note:'The easiest big Vienna landmark to reach from this side of the city.', mapQuery:'Schonbrunn Palace Vienna'},{name:'Mariahilfer Strasse', type:'Shopping and hangout', note:'Useful for a long café-and-shopping walk before heading deeper into the centre.', mapQuery:'Mariahilfer Strasse Vienna'},{name:'Naschmarkt', type:'Market and food stop', note:'Still central enough for a dedicated outing if you want market energy and casual dining.', mapQuery:'Naschmarkt Vienna'}], plans:[['28 Jul','Check in & rest'],['29 Jul','24-hour hop-on hop-off bus'],['30 Jul','Day trip to Bratislava']], map:'https://www.google.com/maps/search/?api=1&query=Leonardo+Hotel+Vienna+City+West' },
  { type:'transfer', start:'2026-07-31', end:'2026-07-31', icon:'🚆', label:'International rail', title:'Vienna → Budapest', meta:'31 Jul · ~3h 20m', summary:'Vienna Central to Budapest', details:[['Board','Vienna Central'],['Cross','Austria → Hungary'],['Arrive','Budapest']], map:'https://www.google.com/maps/dir/?api=1&origin=Vienna+Central+Station&destination=Budapest+Keleti+Station&travelmode=transit' },
  { type:'stay', start:'2026-07-31', end:'2026-08-03', icon:'🏨', city:'Budapest', country:'Hungary', title:'Budapest', meta:'31 Jul–03 Aug · 3 nights', hotel:'Danubius Erzsébet City Center', room:'2 Superior Double Rooms · Breakfast included', address:'[Károlyi Mihály u. 11–15](https://www.google.com/maps/search/K%C3%A1rolyi%0D%0A+Mih%C3%A1ly+u.+11%E2%80%9315?entry=gmail&source=g), 1053 Budapest', image:'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=1200&q=85', about:'A magnificent Danube city split between hilly Buda and lively Pest, rich in architecture, thermal baths and river views.', facts:['Language · Hungarian','Currency · HUF','Avg July · 28°C'], highlights:['Parliament','Castle Hill','Danube Promenade'], nearby:[{name:'Vaci utca', type:'City-centre walk', note:'A very easy pedestrian street from the hotel for shopping, cafes and first orientation.', mapQuery:'Vaci utca Budapest'},{name:'Central Market Hall', type:'Local market', note:'The best nearby market stop for produce, paprika and a more everyday Budapest feel.', mapQuery:'Central Market Hall Budapest'},{name:'Duna Corso', type:'River promenade', note:'A simple central stroll for Danube views and evening riverfront atmosphere.', mapQuery:'Duna Corso Budapest'},{name:'Szimpla Kert and the Jewish Quarter', type:'Evening hangout', note:'Best for Budapest’s ruin-bar energy and a more local night-time scene.', mapQuery:'Szimpla Kert Budapest'}], plans:[['31 Jul','Check in & rest'],['01 Aug','Hop-on hop-off & historic walking tour'],['02 Aug','Danube cruise with audio guide']], map:'https://www.google.com/maps/search/?api=1&query=Danubius+Erzs%C3%A9bet+City+Center+Budapest' },
  { type:'flight', start:'2026-08-03', end:'2026-08-03', icon:'✈', label:'Departure', title:'Budapest → London', meta:'03 Aug · 17:30', summary:'Airport transfer included', details:[['Checkout','By 12:00'],['Transfer','Hotel to Budapest Airport'],['Departure','17:30 to London']], map:'https://www.google.com/maps/search/?api=1&query=Budapest+Ferenc+Liszt+International+Airport' }
];

const hotelMetadata = {
  'Hilton Zurich Airport': ['AV2085180324652','[hilton.com](http://hilton.com/)'],
  'Radisson Blu Lucerne': ['AV2092180284727','[radissonhotels.com](http://radissonhotels.com/)'],
  'Hotel Continental': ['AV203467991234','[hotelcontinental.ch](http://hotelcontinental.ch/)'],
  'Mercure Zürich City': ['AV201145453490','[all.accor.com](http://all.accor.com/)'],
  'PLAZA Premium Salzburg': ['AV224566801252','[plazahotels.de](http://plazahotels.de/)'],
  'Leonardo Hotel Vienna City West': ['AV2135670235698','[leonardo-hotels.com](http://leonardo-hotels.com/)'],
  'Danubius Erzsébet City Center': ['AV2031180984322','[danubiushotels.com](http://danubiushotels.com/)']
};

events.filter(event=>event.type==='stay').forEach(event=>[event.confirmation,event.logo]=hotelMetadata[event.hotel]);

const monthNames=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const dateOf=value=>{const[y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d)};
const today=()=>{const value=new Date();value.setHours(0,0,0,0);return value};
const eventStatus=(event,now)=>dateOf(event.end)<now?'complete':dateOf(event.start)<=now&&dateOf(event.end)>=now?'current':'upcoming';
const mapLink=url=>`<a class="map-link" href="${url}" target="_blank" rel="noopener">Open in Google Maps <span>↗</span></a>`;

// Convert inline markdown links from the data source into clickable HTML.
const parseMarkdownLinks=text=>text.replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener" class="inline-map-link">$1</a>');

const formatShortDate=value=>{const date=dateOf(value);return `${String(date.getDate()).padStart(2,'0')} ${monthNames[date.getMonth()]}`};
const formatDateRange=(start,end)=>start===end?formatShortDate(start):`${formatShortDate(start)} - ${formatShortDate(end)}`;
const placeMapLink=query=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;

function travelCard(event,status){return `<details class="timeline-event travel-event ${status}"><summary><span class="event-logo ${event.type}">${event.icon}</span><span class="summary-copy"><small>${event.label}</small><strong>${event.title}</strong><span class="summary-dates">${formatDateRange(event.start,event.end)}</span><span>${event.meta} · ${event.summary}</span></span><span class="chevron">⌄</span></summary><div class="travel-details">${event.details.map(([label,value])=>`<div><small>${label}</small><strong>${value}</strong></div>`).join('')}</div><div class="event-actions">${mapLink(event.map)}</div></details>`}

function stayCard(event,status,index){
  const logoDomain=(event.logo.match(/\[([^\]]+)\]/)?.[1]||event.logo);
  const logo=`https://www.google.com/s2/favicons?domain=${logoDomain}&sz=128`;
  const formattedAddress=parseMarkdownLinks(event.address);
  return `<article class="timeline-event city-event ${status}"><button class="city-visual" data-city="${index}" style="background-image:linear-gradient(90deg,rgba(8,31,38,.76),rgba(8,31,38,.08)),url('${event.image}')" aria-label="Open ${event.city} city guide"><span><small>${event.country}</small><strong>${event.city}</strong><em>Discover the city ↗</em></span></button><div class="city-body"><div class="stay-meta"><span class="stay-chip">Hotel stay</span><strong>${formatDateRange(event.start,event.end)}</strong><span>${event.meta}</span></div><details class="hotel-details"><summary class="stay-header"><span class="hotel-logo"><img src="${logo}" alt="${event.hotel} logo" /></span><span class="hotel-summary"><small>${event.city} · Booking ${event.confirmation}</small><strong>${event.hotel}</strong><span class="address-container">⌖ ${formattedAddress}</span></span><span class="chevron">⌄</span></summary><div class="hotel-expanded"><p>${event.room}</p><div class="plan-list">${event.plans.map(([date,plan])=>`<div><time>${date}</time><span>${plan}</span></div>`).join('')}</div><div class="city-footer"><span>Check-in 14:00 · Checkout 12:00</span>${mapLink(event.map)}</div></div></details></div></article>`;
}

function renderTimeline(){const now=today(),hidePast=document.querySelector('#hidePast').checked,query=document.querySelector('#searchInput').value.toLowerCase().trim();let shown=0;document.querySelector('#timeline').innerHTML=events.map((event,index)=>{const status=eventStatus(event,now),searchable=`${event.type} ${event.title} ${event.hotel||''} ${event.summary||''} ${(event.plans||[]).flat().join(' ')} ${(event.nearby||[]).map(place=>`${place.name} ${place.note}`).join(' ')}`.toLowerCase(),hidden=(hidePast&&status==='complete')||(query&&!searchable.includes(query));if(!hidden)shown++;return `<div class="timeline-row ${status}" ${hidden?'hidden':''}>${event.type==='stay'?stayCard(event,status,index):travelCard(event,status)}</div>`}).join('');document.querySelector('#emptyState').hidden=shown>0;document.querySelectorAll('[data-city]').forEach(button=>button.addEventListener('click',()=>openCity(Number(button.dataset.city))));updateStatus(now)}

function updateStatus(now){const next=events.find(event=>dateOf(event.end)>=now),completed=events.filter(event=>dateOf(event.end)<now).length,current=events.find(event=>eventStatus(event,now)==='current'),percent=Math.round(completed/events.length*100),nextDetails=next?.meta.split(' · ').slice(1).join(' · ');document.querySelector('#todayLabel').textContent=now.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'});document.querySelector('#status-title').textContent=current?`Now: ${current.title}`:now<dateOf(events[0].start)?'The adventure begins tomorrow':'Journey complete';document.querySelector('#nextUp').textContent=next?.title||'Journey complete';document.querySelector('#nextUpDate').textContent=next?`${formatDateRange(next.start,next.end)}${nextDetails?` · ${nextDetails}`:''}`:'Until next time';document.querySelector('#progressLabel').textContent=`${percent}% complete`;document.querySelector('#progressBar').style.width=`${percent}%`}

function openCity(index){
  const city=events[index];
  document.querySelector('#dialogImage').style.backgroundImage=`url('${city.image}')`;
  document.querySelector('#dialogCountry').textContent=city.country;
  document.querySelector('#dialogTitle').textContent=city.city;
  document.querySelector('#dialogDates').textContent=`${formatDateRange(city.start,city.end)} · Staying at ${city.hotel}`;
  document.querySelector('#dialogAbout').textContent=city.about;
  document.querySelector('#dialogFacts').innerHTML=city.facts.map(fact=>{const[label,val]=fact.split(' · ');return `<span class="fact-bubble"><strong>${label}:</strong> ${val}</span>`}).join('');
  document.querySelector('#dialogHighlights').innerHTML=`<small>Worth knowing</small><div class="highlights-wrap">${city.highlights.map(item=>`<span>${item}</span>`).join('')}</div>`;
  document.querySelector('#dialogPlaces').innerHTML=city.nearby.map(place=>`<article class="place-card"><div><small>${place.type}</small><strong>${place.name}</strong><p>${place.note}</p></div><a href="${placeMapLink(place.mapQuery)}" target="_blank" rel="noopener" class="place-link">Open map ↗</a></article>`).join('');
  document.querySelector('#dialogMap').href=city.map;
  document.querySelector('#cityDialog').showModal();
}

document.querySelector('#searchInput').addEventListener('input',renderTimeline);
document.querySelector('#hidePast').addEventListener('change',renderTimeline);
document.querySelector('.dialog-close').addEventListener('click',()=>document.querySelector('#cityDialog').close());
document.querySelector('#cityDialog').addEventListener('click',event=>{if(event.target.id==='cityDialog')event.target.close()});
document.querySelector('#shareButton').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);toast('Itinerary link copied')}catch{toast('Copy the page address to share')}});

function toast(message){const element=document.querySelector('#toast');element.textContent=message;element.classList.add('visible');setTimeout(()=>element.classList.remove('visible'),2500)}

renderTimeline();
